//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_and_Guide_to_GilgitBaltistan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public string Name { get; set; }
        public string Contact_Number { get; set; }
        public string Email_Address { get; set; }
        public string Current_Address { get; set; }
        public string Payment_Method { get; set; }
        public decimal Advanced_Payment { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public byte[] Payment_Proof { get; set; }
    }
}
