//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_and_Guide_to_GilgitBaltistan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string Gender { get; set; }
        public string Name { get; set; }
        public string Contact_Number { get; set; }
        public string EmailAddress { get; set; }
        public string Current_Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public System.DateTime Added_On { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
    }
}
