//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_and_Guide_to_GilgitBaltistan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int LocationId { get; set; }
        public string Lacation_Name { get; set; }
        public string Google_Map_url_ { get; set; }
        public string City { get; set; }
        public string Top_Picnic_Points { get; set; }
        public string Top_Hotels { get; set; }
        public string Details { get; set; }
    }
}
